### ISSUE TITLE
Scheduling is not disabled on the master node

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kops#68] opened 2017-04-28 20:59 UTC
found scheduling is enabled on the Master node after cluster deployment.
expecting `SchedulingDisabled` status on master node. pods are getting created on the master node.

```
+ kubectl get nodes
NAME                                                  STATUS         AGE       VERSION
master-vmware-zone.masters.kubernetes.skydns.local1   Ready,master   1h        v1.5.2
nodes.kubernetes.skydns.local1                        Ready,node     1h        v1.5.2
nodes.kubernetes.skydns.local2                        Ready,node     1h        v1.5.2
```

**Comment by prashima** [comment] 2017-06-06 17:39
Discussed this offline with @divyenpatel. The way kops makes sure that unwanted pods are not scheduled on master node it through taints and toleration. So a pod spec that doesn't bear appropriate toleration will not be scheduled on master.

Closing this issue, it's not a bug.

**Closed as completed by prashima** 2017-06-06 17:39 UTC
